function removePadding(p){var y=p.byteLength,D=y&&(new DataView(p)).getUint8(y-1);return D?p.slice(0,y-D):p}
function AESDecryptor(){return{constructor:function(){this.rcon=[0,1,2,4,8,16,32,64,128,27,54];this.subMix=[new Uint32Array(256),new Uint32Array(256),new Uint32Array(256),new Uint32Array(256)];this.invSubMix=[new Uint32Array(256),new Uint32Array(256),new Uint32Array(256),new Uint32Array(256)];this.sBox=new Uint32Array(256);this.invSBox=new Uint32Array(256);this.key=new Uint32Array(0);this.initTable()},uint8ArrayToUint32Array_:function(p){p=new DataView(p);for(var y=new Uint32Array(4),D=0;4>D;D++)y[D]=
p.getUint32(4*D);return y},initTable:function(){var p=this.sBox,y=this.invSBox,D=this.subMix,l=D[0],e=D[1],d=D[2];D=D[3];var b=this.invSubMix,a=b[0],c=b[1],k=b[2];b=b[3];var g=new Uint32Array(256),m=0,n=0,t;for(t=0;256>t;t++)g[t]=128>t?t<<1:t<<1^283;for(t=0;256>t;t++){var h=n^n<<1^n<<2^n<<3^n<<4;h=h>>>8^h&255^99;p[m]=h;y[h]=m;var f=g[m],r=g[f],C=g[r],u=257*g[h]^16843008*h;l[m]=u<<24|u>>>8;e[m]=u<<16|u>>>16;d[m]=u<<8|u>>>24;D[m]=u;u=16843009*C^65537*r^257*f^16843008*m;a[h]=u<<24|u>>>8;c[h]=u<<16|u>>>
16;k[h]=u<<8|u>>>24;b[h]=u;m?(m=f^g[g[g[C^f]]],n^=g[g[n]]):m=n=1}},expandKey:function(p){p=this.uint8ArrayToUint32Array_(p);for(var y=!0,D=0;D<p.length&&y;)y=p[D]===this.key[D],D++;if(!y){this.key=p;var l=this.keySize=p.length;if(4!==l&&6!==l&&8!==l)throw Error("Invalid aes key size="+l);y=this.ksRows=4*(l+6+1);D=this.keySchedule=new Uint32Array(y);var e=this.invKeySchedule=new Uint32Array(y),d=this.sBox,b=this.rcon;var a=this.invSubMix;var c=a[0],k=a[1],g=a[2],m=a[3];for(a=0;a<y;a++)if(a<l)var n=
D[a]=p[a];else 0===a%l?(n=n<<8|n>>>24,n=d[n>>>24]<<24|d[n>>>16&255]<<16|d[n>>>8&255]<<8|d[n&255],n^=b[a/l|0]<<24):6<l&&4===a%l&&(n=d[n>>>24]<<24|d[n>>>16&255]<<16|d[n>>>8&255]<<8|d[n&255]),D[a]=n=(D[a-l]^n)>>>0;for(p=0;p<y;p++)a=y-p,n=p&3?D[a]:D[a-4],e[p]=4>p||4>=a?n:c[d[n>>>24]]^k[d[n>>>16&255]]^g[d[n>>>8&255]]^m[d[n&255]],e[p]>>>=0}},networkToHostOrderSwap:function(p){return p<<24|(p&65280)<<8|(p&16711680)>>8|p>>>24},decrypt:function(p,y,D,l){var e=this.keySize+6,d=this.invKeySchedule,b=this.invSBox,
a=this.invSubMix,c=a[0],k=a[1],g=a[2];a=a[3];var m=this.uint8ArrayToUint32Array_(D);D=m[0];var n=m[1],t=m[2];m=m[3];p=new Int32Array(p);for(var h=new Int32Array(p.length),f,r,C,u,A,E,w,q,z,B,J,G,x,H=this.networkToHostOrderSwap;y<p.length;){q=H(p[y]);z=H(p[y+1]);B=H(p[y+2]);J=H(p[y+3]);A=q^d[0];E=J^d[1];w=B^d[2];u=z^d[3];G=4;for(x=1;x<e;x++)f=c[A>>>24]^k[E>>16&255]^g[w>>8&255]^a[u&255]^d[G],r=c[E>>>24]^k[w>>16&255]^g[u>>8&255]^a[A&255]^d[G+1],C=c[w>>>24]^k[u>>16&255]^g[A>>8&255]^a[E&255]^d[G+2],u=
c[u>>>24]^k[A>>16&255]^g[E>>8&255]^a[w&255]^d[G+3],A=f,E=r,w=C,G+=4;f=b[A>>>24]<<24^b[E>>16&255]<<16^b[w>>8&255]<<8^b[u&255]^d[G];r=b[E>>>24]<<24^b[w>>16&255]<<16^b[u>>8&255]<<8^b[A&255]^d[G+1];C=b[w>>>24]<<24^b[u>>16&255]<<16^b[A>>8&255]<<8^b[E&255]^d[G+2];u=b[u>>>24]<<24^b[A>>16&255]<<16^b[E>>8&255]<<8^b[w&255]^d[G+3];h[y]=H(f^D);h[y+1]=H(u^n);h[y+2]=H(C^t);h[y+3]=H(r^m);D=q;n=z;t=B;m=J;y+=4}return l?removePadding(h.buffer):h.buffer},destroy:function(){this.rcon=this.invKeySchedule=this.keySchedule=
this.invSubMix=this.subMix=this.invSBox=this.sBox=this.ksRows=this.keySize=this.key=void 0}}}
(function(p){"object"===typeof exports&&"undefined"!==typeof module?module.exports=p():"function"===typeof define&&define.amd?define([],p):("undefined"!==typeof window?window:"undefined"!==typeof global?global:"undefined"!==typeof self?self:this).muxjs=p()})(function(){return function(){function p(y,D,l){function e(a,c){if(!D[a]){if(!y[a]){var k="function"==typeof require&&require;if(!c&&k)return k(a,!0);if(d)return d(a,!0);k=Error("Cannot find module '"+a+"'");throw k.code="MODULE_NOT_FOUND",k;}k=
D[a]={exports:{}};y[a][0].call(k.exports,function(g){return e(y[a][1][g]||g)},k,k.exports,p,y,D,l)}return D[a].exports}for(var d="function"==typeof require&&require,b=0;b<l.length;b++)e(l[b]);return e}return p}()({1:[function(p,y,D){D=p(31);var l=p(2);var e=function(){var d=new Uint8Array,b=0;e.prototype.init.call(this);this.setTimestamp=function(a){b=a};this.push=function(a){var c=0;if(d.length){var k=d.length;d=new Uint8Array(a.byteLength+k);d.set(d.subarray(0,k));d.set(a,k)}else d=a;for(;3<=d.length-
c;)if(73===d[c]&&68===d[c+1]&&51===d[c+2]){if(10>d.length-c)break;a=l.parseId3TagSize(d,c);if(c+a>d.length)break;k={type:"timed-metadata",data:d.subarray(c,c+a)};this.trigger("data",k);c+=a}else if(255===(d[c]&255)&&240===(d[c+1]&240)){if(7>d.length-c)break;a=l.parseAdtsSize(d,c);if(c+a>d.length)break;k={type:"audio",data:d.subarray(c,c+a),pts:b,dts:b};this.trigger("data",k);c+=a}else c++;d=0<d.length-c?d.subarray(c):new Uint8Array};this.reset=function(){d=new Uint8Array;this.trigger("reset")};this.endTimeline=
function(){d=new Uint8Array;this.trigger("endedtimeline")}};e.prototype=new D;y.exports=e},{2:2,31:31}],2:[function(p,y,D){var l=[96E3,88200,64E3,48E3,44100,32E3,24E3,22050,16E3,12E3,11025,8E3,7350],e=function(a,c){var k=a[c+6]<<21|a[c+7]<<14|a[c+8]<<7|a[c+9],g=a[c+5];k=0<=k?k:0;return(g&16)>>4?k+20:k+10},d=function(a,c){if(10>a.length-c||73!==a[c]||68!==a[c+1]||51!==a[c+2])return c;c+=e(a,c);return d(a,c)},b=function(a){return a[0]<<21|a[1]<<14|a[2]<<7|a[3]};y.exports={isLikelyAacData:function(a){var c=
d(a,0);return a.length>=c+2&&255===(a[c]&255)&&240===(a[c+1]&240)&&16===(a[c+1]&22)},parseId3TagSize:e,parseAdtsSize:function(a,c){return a[c+3]&6144|a[c+4]<<3|(a[c+5]&224)>>5},parseType:function(a,c){return 73===a[c]&&68===a[c+1]&&51===a[c+2]?"timed-metadata":a[c]&1&&240===(a[c+1]&240)?"audio":null},parseSampleRate:function(a){for(var c=0;c+5<a.length;)if(255!==a[c]||240!==(a[c+1]&246))c++;else return l[(a[c+2]&60)>>>2];return null},parseAacTimestamp:function(a){var c=10;a[5]&64&&(c=c+4+b(a.subarray(10,
14)));do{var k=b(a.subarray(c+4,c+8));if(1>k)break;var g=String.fromCharCode(a[c],a[c+1],a[c+2],a[c+3]);if("PRIV"===g){g=a.subarray(c+10,c+k+10);for(var m=0;m<g.byteLength;m++)if(0===g[m]){var n=unescape,t,h=g,f=m,r="";for(t=0;t<f;t++)r+="%"+("00"+h[t].toString(16)).slice(-2);if("com.apple.streaming.transportStreamTimestamp"===n(r))return a=g.subarray(m+1),c=(a[3]&1)<<30|a[4]<<22|a[5]<<14|a[6]<<6|a[7]>>>2,c*=4,c+=a[7]&3;break}}c+=10;c+=k}while(c<a.byteLength);return null}}},{}],3:[function(p,y,D){D=
p(31);var l=p(29).ONE_SECOND_IN_TS,e=[96E3,88200,64E3,48E3,44100,32E3,24E3,22050,16E3,12E3,11025,8E3,7350];var d=function(b){var a,c=0;d.prototype.init.call(this);this.push=function(k){var g=0;b||(c=0);if("audio"===k.type){if(a){var m=a;a=new Uint8Array(m.byteLength+k.data.byteLength);a.set(m);a.set(k.data,m.byteLength)}else a=k.data;for(;g+5<a.length;)if(255!==a[g]||240!==(a[g+1]&246))g++;else{m=2*(~a[g+1]&1);var n=(a[g+3]&3)<<11|a[g+4]<<3|(a[g+5]&224)>>5;var t=1024*((a[g+6]&3)+1);var h=t*l/e[(a[g+
2]&60)>>>2];n=g+n;if(a.byteLength<n)break;this.trigger("data",{pts:k.pts+c*h,dts:k.dts+c*h,sampleCount:t,audioobjecttype:(a[g+2]>>>6&3)+1,channelcount:(a[g+2]&1)<<2|(a[g+3]&192)>>>6,samplerate:e[(a[g+2]&60)>>>2],samplingfrequencyindex:(a[g+2]&60)>>>2,samplesize:16,data:a.subarray(g+7+m,n)});c++;if(a.byteLength===n){a=void 0;break}a=a.subarray(n)}}};this.flush=function(){c=0;this.trigger("done")};this.reset=function(){a=void 0;this.trigger("reset")};this.endTimeline=function(){a=void 0;this.trigger("endedtimeline")}};
d.prototype=new D;y.exports=d},{29:29,31:31}],4:[function(p,y,D){D=p(31);var l=p(30);var e=function(){var a=0,c,k;e.prototype.init.call(this);this.push=function(g){if(k){var m=new Uint8Array(k.byteLength+g.data.byteLength);m.set(k);m.set(g.data,k.byteLength);k=m}else k=g.data;for(g=k.byteLength;a<g-3;a++)if(1===k[a+2]){c=a+5;break}for(;c<g;)switch(k[c]){case 0:if(0!==k[c-1]){c+=2;break}else if(0!==k[c-2]){c++;break}a+3!==c-2&&this.trigger("data",k.subarray(a+3,c-2));do c++;while(1!==k[c]&&c<g);a=
c-2;c+=3;break;case 1:if(0!==k[c-1]||0!==k[c-2]){c+=3;break}this.trigger("data",k.subarray(a+3,c-2));a=c-2;c+=3;break;default:c+=3}k=k.subarray(a);c-=a;a=0};this.reset=function(){k=null;a=0;this.trigger("reset")};this.flush=function(){k&&3<k.byteLength&&this.trigger("data",k.subarray(a+3));k=null;a=0;this.trigger("done")};this.endTimeline=function(){this.flush();this.trigger("endedtimeline")}};e.prototype=new D;var d={100:!0,110:!0,122:!0,244:!0,44:!0,83:!0,86:!0,118:!0,128:!0,138:!0,139:!0,134:!0};
var b=function(){var a=new e,c,k,g;b.prototype.init.call(this);var m=this;this.push=function(f){"video"===f.type&&(c=f.trackId,k=f.pts,g=f.dts,a.push(f))};a.on("data",function(f){var r={trackId:c,pts:k,dts:g,data:f};switch(f[0]&31){case 5:r.nalUnitType="slice_layer_without_partitioning_rbsp_idr";break;case 6:r.nalUnitType="sei_rbsp";r.escapedRBSP=t(f.subarray(1));break;case 7:r.nalUnitType="seq_parameter_set_rbsp";r.escapedRBSP=t(f.subarray(1));r.config=h(r.escapedRBSP);break;case 8:r.nalUnitType=
"pic_parameter_set_rbsp";break;case 9:r.nalUnitType="access_unit_delimiter_rbsp"}m.trigger("data",r)});a.on("done",function(){m.trigger("done")});a.on("partialdone",function(){m.trigger("partialdone")});a.on("reset",function(){m.trigger("reset")});a.on("endedtimeline",function(){m.trigger("endedtimeline")});this.flush=function(){a.flush()};this.partialFlush=function(){a.partialFlush()};this.reset=function(){a.reset()};this.endTimeline=function(){a.endTimeline()};var n=function(f,r){var C=8,u=8,A;
for(A=0;A<f;A++)0!==u&&(u=r.readExpGolomb(),u=(C+u+256)%256),C=0===u?C:u};var t=function(f){for(var r=f.byteLength,C=[],u=1,A;u<r-2;)0===f[u]&&0===f[u+1]&&3===f[u+2]?(C.push(u+2),u+=2):u++;if(0===C.length)return f;r-=C.length;A=new Uint8Array(r);var E=0;for(u=0;u<r;E++,u++)E===C[0]&&(E++,C.shift()),A[u]=f[E];return A};var h=function(f){var r=0,C=0,u=0,A=0,E=1;f=new l(f);var w=f.readUnsignedByte();var q=f.readUnsignedByte();var z=f.readUnsignedByte();f.skipUnsignedExpGolomb();if(d[w]){var B=f.readUnsignedExpGolomb();
3===B&&f.skipBits(1);f.skipUnsignedExpGolomb();f.skipUnsignedExpGolomb();f.skipBits(1);if(f.readBoolean()){var J=3!==B?8:12;for(B=0;B<J;B++)f.readBoolean()&&(6>B?n(16,f):n(64,f))}}f.skipUnsignedExpGolomb();B=f.readUnsignedExpGolomb();if(0===B)f.readUnsignedExpGolomb();else if(1===B)for(f.skipBits(1),f.skipExpGolomb(),f.skipExpGolomb(),J=f.readUnsignedExpGolomb(),B=0;B<J;B++)f.skipExpGolomb();f.skipUnsignedExpGolomb();f.skipBits(1);B=f.readUnsignedExpGolomb();J=f.readUnsignedExpGolomb();var G=f.readBits(1);
0===G&&f.skipBits(1);f.skipBits(1);f.readBoolean()&&(r=f.readUnsignedExpGolomb(),C=f.readUnsignedExpGolomb(),u=f.readUnsignedExpGolomb(),A=f.readUnsignedExpGolomb());if(f.readBoolean()&&f.readBoolean()){var x=f.readUnsignedByte();switch(x){case 1:var H=[1,1];break;case 2:H=[12,11];break;case 3:H=[10,11];break;case 4:H=[16,11];break;case 5:H=[40,33];break;case 6:H=[24,11];break;case 7:H=[20,11];break;case 8:H=[32,11];break;case 9:H=[80,33];break;case 10:H=[18,11];break;case 11:H=[15,11];break;case 12:H=
[64,33];break;case 13:H=[160,99];break;case 14:H=[4,3];break;case 15:H=[3,2];break;case 16:H=[2,1];break;case 255:H=[f.readUnsignedByte()<<8|f.readUnsignedByte(),f.readUnsignedByte()<<8|f.readUnsignedByte()]}H&&(E=H[0]/H[1])}return{profileIdc:w,levelIdc:z,profileCompatibility:q,width:Math.ceil((16*(B+1)-2*r-2*C)*E),height:(2-G)*(J+1)*16-2*u-2*A,sarRatio:H}}};b.prototype=new D;y.exports={H264Stream:b,NalByteStream:e}},{30:30,31:31}],5:[function(p,y,D){y.exports=["audioobjecttype","channelcount","samplerate",
"samplingfrequencyindex","samplesize"]},{}],6:[function(p,y,D){y.exports="width height profileIdc levelIdc profileCompatibility sarRatio".split(" ")},{}],7:[function(p,y,D){var l=[33,16,5,32,164,27],e=[33,65,108,84,1,2,4,8,168,2,4,8,17,191,252],d=function(c){for(var k=[];c--;)k.push(0);return k},b=function(c){return Object.keys(c).reduce(function(k,g){k[g]=new Uint8Array(c[g].reduce(function(m,n){return m.concat(n)},[]));return k},{})},a;y.exports=function(){if(!a){var c={96E3:[l,[227,64],d(154),
[56]],88200:[l,[231],d(170),[56]],64E3:[l,[248,192],d(240),[56]],48E3:[l,[255,192],d(268),[55,148,128],d(54),[112]],44100:[l,[255,192],d(268),[55,163,128],d(84),[112]],32E3:[l,[255,192],d(268),[55,234],d(226),[112]],24E3:[l,[255,192],d(268),[55,255,128],d(268),[111,112],d(126),[224]],16E3:[l,[255,192],d(268),[55,255,128],d(268),[111,255],d(269),[223,108],d(195),[1,192]],12E3:[e,d(268),[3,127,248],d(268),[6,255,240],d(268),[13,255,224],d(268),[27,253,128],d(259),[56]],11025:[e,d(268),[3,127,248],d(268),
[6,255,240],d(268),[13,255,224],d(268),[27,255,192],d(268),[55,175,128],d(108),[112]],8E3:[e,d(268),[3,121,16],d(47),[7]]};a=b(c)}return a}},{}],8:[function(p,y,D){D=p(31);var l=p(23),e=function(){e.prototype.init.call(this);this.captionPackets_=[];this.ccStreams_=[new k(0,0),new k(0,1),new k(1,0),new k(1,1)];this.reset();this.ccStreams_.forEach(function(g){g.on("data",this.trigger.bind(this,"data"));g.on("partialdone",this.trigger.bind(this,"partialdone"));g.on("done",this.trigger.bind(this,"done"))},
this)};e.prototype=new D;e.prototype.push=function(g){if("sei_rbsp"===g.nalUnitType){var m=l.parseSei(g.escapedRBSP);m.payloadType===l.USER_DATA_REGISTERED_ITU_T_T35&&(m=l.parseUserData(m))&&(g.dts<this.latestDts_?this.ignoreNextEqualDts_=!0:g.dts===this.latestDts_&&this.ignoreNextEqualDts_?(this.numSameDts_--,this.numSameDts_||(this.ignoreNextEqualDts_=!1)):(m=l.parseCaptionPackets(g.pts,m),this.captionPackets_=this.captionPackets_.concat(m),this.latestDts_!==g.dts&&(this.numSameDts_=0),this.numSameDts_++,
this.latestDts_=g.dts))}};e.prototype.flushCCStreams=function(g){this.ccStreams_.forEach(function(m){return"flush"===g?m.flush():m.partialFlush()},this)};e.prototype.flushStream=function(g){this.captionPackets_.length&&(this.captionPackets_.forEach(function(m,n){m.presortIndex=n}),this.captionPackets_.sort(function(m,n){return m.pts===n.pts?m.presortIndex-n.presortIndex:m.pts-n.pts}),this.captionPackets_.forEach(function(m){2>m.type&&this.dispatchCea608Packet(m)},this),this.captionPackets_.length=
0);this.flushCCStreams(g)};e.prototype.flush=function(){return this.flushStream("flush")};e.prototype.partialFlush=function(){return this.flushStream("partialFlush")};e.prototype.reset=function(){this.latestDts_=null;this.ignoreNextEqualDts_=!1;this.numSameDts_=0;this.activeCea608Channel_=[null,null];this.ccStreams_.forEach(function(g){g.reset()})};e.prototype.dispatchCea608Packet=function(g){this.setsTextOrXDSActive(g)?this.activeCea608Channel_[g.type]=null:this.setsChannel1Active(g)?this.activeCea608Channel_[g.type]=
0:this.setsChannel2Active(g)&&(this.activeCea608Channel_[g.type]=1);null!==this.activeCea608Channel_[g.type]&&this.ccStreams_[(g.type<<1)+this.activeCea608Channel_[g.type]].push(g)};e.prototype.setsChannel1Active=function(g){return 4096===(g.ccData&30720)};e.prototype.setsChannel2Active=function(g){return 6144===(g.ccData&30720)};e.prototype.setsTextOrXDSActive=function(g){return 256===(g.ccData&28928)||4138===(g.ccData&30974)||6186===(g.ccData&30974)};var d={42:225,92:233,94:237,95:243,96:250,123:231,
124:247,125:209,126:241,127:9608,304:174,305:176,306:189,307:191,308:8482,309:162,310:163,311:9834,312:224,313:160,314:232,315:226,316:234,317:238,318:244,319:251,544:193,545:201,546:211,547:218,548:220,549:252,550:8216,551:161,552:42,553:39,554:8212,555:169,556:8480,557:8226,558:8220,559:8221,560:192,561:194,562:199,563:200,564:202,565:203,566:235,567:206,568:207,569:239,570:212,571:217,572:249,573:219,574:171,575:187,800:195,801:227,802:205,803:204,804:236,805:210,806:242,807:213,808:245,809:123,
810:125,811:92,812:94,813:95,814:124,815:126,816:196,817:228,818:214,819:246,820:223,821:165,822:164,823:9474,824:197,825:229,826:216,827:248,828:9484,829:9488,830:9492,831:9496},b=function(g){if(null===g)return"";g=d[g]||g;return String.fromCharCode(g)},a=[4352,4384,4608,4640,5376,5408,5632,5664,5888,5920,4096,4864,4896,5120,5152],c=function(){for(var g=[],m=15;m--;)g.push("");return g},k=function(g,m){k.prototype.init.call(this);this.field_=g||0;this.dataChannel_=m||0;this.name_="CC"+((this.field_<<
1|this.dataChannel_)+1);this.setConstants();this.reset();this.push=function(n){var t=n.ccData&32639;if(t===this.lastControlCode_)this.lastControlCode_=null;else{4096===(t&61440)?this.lastControlCode_=t:t!==this.PADDING_&&(this.lastControlCode_=null);var h=t>>>8;var f=t&255;t!==this.PADDING_&&(t===this.RESUME_CAPTION_LOADING_?this.mode_="popOn":t===this.END_OF_CAPTION_?(this.mode_="popOn",this.clearFormatting(n.pts),this.flushDisplayed(n.pts),f=this.displayed_,this.displayed_=this.nonDisplayed_,this.nonDisplayed_=
f,this.startPts_=n.pts):t===this.ROLL_UP_2_ROWS_?(this.rollUpRows_=2,this.setRollUp(n.pts)):t===this.ROLL_UP_3_ROWS_?(this.rollUpRows_=3,this.setRollUp(n.pts)):t===this.ROLL_UP_4_ROWS_?(this.rollUpRows_=4,this.setRollUp(n.pts)):t===this.CARRIAGE_RETURN_?(this.clearFormatting(n.pts),this.flushDisplayed(n.pts),this.shiftRowsUp_(),this.startPts_=n.pts):t===this.BACKSPACE_?"popOn"===this.mode_?this.nonDisplayed_[this.row_]=this.nonDisplayed_[this.row_].slice(0,-1):this.displayed_[this.row_]=this.displayed_[this.row_].slice(0,
-1):t===this.ERASE_DISPLAYED_MEMORY_?(this.flushDisplayed(n.pts),this.displayed_=c()):t===this.ERASE_NON_DISPLAYED_MEMORY_?this.nonDisplayed_=c():t===this.RESUME_DIRECT_CAPTIONING_?("paintOn"!==this.mode_&&(this.flushDisplayed(n.pts),this.displayed_=c()),this.mode_="paintOn",this.startPts_=n.pts):this.isSpecialCharacter(h,f)?(t=b((h&3)<<8|f),this[this.mode_](n.pts,t),this.column_++):this.isExtCharacter(h,f)?("popOn"===this.mode_?this.nonDisplayed_[this.row_]=this.nonDisplayed_[this.row_].slice(0,
-1):this.displayed_[this.row_]=this.displayed_[this.row_].slice(0,-1),t=b((h&3)<<8|f),this[this.mode_](n.pts,t),this.column_++):this.isMidRowCode(h,f)?(this.clearFormatting(n.pts),this[this.mode_](n.pts," "),this.column_++,14===(f&14)&&this.addFormatting(n.pts,["i"]),1===(f&1)&&this.addFormatting(n.pts,["u"])):this.isOffsetControlCode(h,f)?this.column_+=f&3:this.isPAC(h,f)?(h=a.indexOf(t&7968),"rollUp"===this.mode_&&(0>h-this.rollUpRows_+1&&(h=this.rollUpRows_-1),this.setRollUp(n.pts,h)),h!==this.row_&&
(this.clearFormatting(n.pts),this.row_=h),f&1&&-1===this.formatting_.indexOf("u")&&this.addFormatting(n.pts,["u"]),16===(t&16)&&(this.column_=4*((t&14)>>1)),this.isColorPAC(f)&&14===(f&14)&&this.addFormatting(n.pts,["i"])):this.isNormalChar(h)&&(0===f&&(f=null),t=b(h),t+=b(f),this[this.mode_](n.pts,t),this.column_+=t.length))}}};k.prototype=new D;k.prototype.flushDisplayed=function(g){var m=this.displayed_.map(function(n){try{return n.trim()}catch(t){return console.error("Skipping malformed caption."),
""}}).join("\n").replace(/^\n+|\n+$/g,"");m.length&&this.trigger("data",{startPts:this.startPts_,endPts:g,text:m,stream:this.name_})};k.prototype.reset=function(){this.mode_="popOn";this.startPts_=this.topRow_=0;this.displayed_=c();this.nonDisplayed_=c();this.lastControlCode_=null;this.column_=0;this.row_=14;this.rollUpRows_=2;this.formatting_=[]};k.prototype.setConstants=function(){0===this.dataChannel_?(this.BASE_=16,this.EXT_=17,this.CONTROL_=(20|this.field_)<<8,this.OFFSET_=23):1===this.dataChannel_&&
(this.BASE_=24,this.EXT_=25,this.CONTROL_=(28|this.field_)<<8,this.OFFSET_=31);this.PADDING_=0;this.RESUME_CAPTION_LOADING_=this.CONTROL_|32;this.END_OF_CAPTION_=this.CONTROL_|47;this.ROLL_UP_2_ROWS_=this.CONTROL_|37;this.ROLL_UP_3_ROWS_=this.CONTROL_|38;this.ROLL_UP_4_ROWS_=this.CONTROL_|39;this.CARRIAGE_RETURN_=this.CONTROL_|45;this.RESUME_DIRECT_CAPTIONING_=this.CONTROL_|41;this.BACKSPACE_=this.CONTROL_|33;this.ERASE_DISPLAYED_MEMORY_=this.CONTROL_|44;this.ERASE_NON_DISPLAYED_MEMORY_=this.CONTROL_|
46};k.prototype.isSpecialCharacter=function(g,m){return g===this.EXT_&&48<=m&&63>=m};k.prototype.isExtCharacter=function(g,m){return(g===this.EXT_+1||g===this.EXT_+2)&&32<=m&&63>=m};k.prototype.isMidRowCode=function(g,m){return g===this.EXT_&&32<=m&&47>=m};k.prototype.isOffsetControlCode=function(g,m){return g===this.OFFSET_&&33<=m&&35>=m};k.prototype.isPAC=function(g,m){return g>=this.BASE_&&g<this.BASE_+8&&64<=m&&127>=m};k.prototype.isColorPAC=function(g){return 64<=g&&79>=g||96<=g&&127>=g};k.prototype.isNormalChar=
function(g){return 32<=g&&127>=g};k.prototype.setRollUp=function(g,m){"rollUp"!==this.mode_&&(this.row_=14,this.mode_="rollUp",this.flushDisplayed(g),this.nonDisplayed_=c(),this.displayed_=c());if(void 0!==m&&m!==this.row_)for(var n=0;n<this.rollUpRows_;n++)this.displayed_[m-n]=this.displayed_[this.row_-n],this.displayed_[this.row_-n]="";void 0===m&&(m=this.row_);this.topRow_=m-this.rollUpRows_+1};k.prototype.addFormatting=function(g,m){this.formatting_=this.formatting_.concat(m);var n=m.reduce(function(t,
h){return t+"<"+h+">"},"");this[this.mode_](g,n)};k.prototype.clearFormatting=function(g){if(this.formatting_.length){var m=this.formatting_.reverse().reduce(function(n,t){return n+"</"+t+">"},"");this.formatting_=[];this[this.mode_](g,m)}};k.prototype.popOn=function(g,m){this.nonDisplayed_[this.row_]+=m};k.prototype.rollUp=function(g,m){this.displayed_[this.row_]+=m};k.prototype.shiftRowsUp_=function(){var g;for(g=0;g<this.topRow_;g++)this.displayed_[g]="";for(g=this.row_+1;15>g;g++)this.displayed_[g]=
"";for(g=this.topRow_;g<this.row_;g++)this.displayed_[g]=this.displayed_[g+1];this.displayed_[this.row_]=""};k.prototype.paintOn=function(g,m){this.displayed_[this.row_]+=m};y.exports={CaptionStream:e,Cea608Stream:k}},{23:23,31:31}],9:[function(p,y,D){D=p(31);var l=p(8),e=p(11),d=p(12).TimestampRolloverStream;var b=function(){var g=new Uint8Array(188),m=0;b.prototype.init.call(this);this.push=function(n){var t=0,h=188;if(m){var f=new Uint8Array(n.byteLength+m);f.set(g.subarray(0,m));f.set(n,m);m=
0}else f=n;for(;h<f.byteLength;)71===f[t]&&71===f[h]?(this.trigger("data",f.subarray(t,h)),t+=188,h+=188):(t++,h++);t<f.byteLength&&(g.set(f.subarray(t),0),m=f.byteLength-t)};this.flush=function(){188===m&&71===g[0]&&(this.trigger("data",g),m=0);this.trigger("done")};this.endTimeline=function(){this.flush();this.trigger("endedtimeline")};this.reset=function(){m=0;this.trigger("reset")}};b.prototype=new D;var a=function(){a.prototype.init.call(this);var g=this;this.packetsWaitingForPmt=[];this.programMapTable=
void 0;var m=function(h,f){var r=0;f.payloadUnitStartIndicator&&(r+=h[r]+1);"pat"===f.type?n(h.subarray(r),f):t(h.subarray(r),f)};var n=function(h,f){f.section_number=h[7];f.last_section_number=h[8];g.pmtPid=(h[10]&31)<<8|h[11];f.pmtPid=g.pmtPid};var t=function(h,f){var r;if(h[5]&1){g.programMapTable={video:null,audio:null,"timed-metadata":{}};var C=3+((h[1]&15)<<8|h[2])-4;for(r=12+((h[10]&15)<<8|h[11]);r<C;){var u=h[r],A=(h[r+1]&31)<<8|h[r+2];u===e.H264_STREAM_TYPE&&null===g.programMapTable.video?
g.programMapTable.video=A:u===e.ADTS_STREAM_TYPE&&null===g.programMapTable.audio?g.programMapTable.audio=A:u===e.METADATA_STREAM_TYPE&&(g.programMapTable["timed-metadata"][A]=u);r+=((h[r+3]&15)<<8|h[r+4])+5}f.programMapTable=g.programMapTable}};this.push=function(h){var f={},r=4;f.payloadUnitStartIndicator=!!(h[1]&64);f.pid=h[1]&31;f.pid<<=8;f.pid|=h[2];1<(h[3]&48)>>>4&&(r+=h[r]+1);if(0===f.pid)f.type="pat",m(h.subarray(r),f),this.trigger("data",f);else if(f.pid===this.pmtPid)for(f.type="pmt",m(h.subarray(r),
f),this.trigger("data",f);this.packetsWaitingForPmt.length;)this.processPes_.apply(this,this.packetsWaitingForPmt.shift());else void 0===this.programMapTable?this.packetsWaitingForPmt.push([h,r,f]):this.processPes_(h,r,f)};this.processPes_=function(h,f,r){r.streamType=r.pid===this.programMapTable.video?e.H264_STREAM_TYPE:r.pid===this.programMapTable.audio?e.ADTS_STREAM_TYPE:this.programMapTable["timed-metadata"][r.pid];r.type="pes";r.data=h.subarray(f);this.trigger("data",r)}};a.prototype=new D;a.STREAM_TYPES=
{h264:27,adts:15};var c=function(){var g=this,m={data:[],size:0},n={data:[],size:0},t={data:[],size:0},h,f=function(r,C,u){var A=new Uint8Array(r.size),E={type:C},w,q=0;if(r.data.length&&!(9>r.size)){E.trackId=r.data[0].pid;for(w=0;w<r.data.length;w++){var z=r.data[w];A.set(z.data,q);q+=z.data.byteLength}E.packetLength=6+(A[4]<<8|A[5]);E.dataAlignmentIndicator=0!==(A[6]&4);w=A[7];w&192&&(E.pts=(A[9]&14)<<27|(A[10]&255)<<20|(A[11]&254)<<12|(A[12]&255)<<5|(A[13]&254)>>>3,E.pts*=4,E.pts+=(A[13]&6)>>>
1,E.dts=E.pts,w&64&&(E.dts=(A[14]&14)<<27|(A[15]&255)<<20|(A[16]&254)<<12|(A[17]&255)<<5|(A[18]&254)>>>3,E.dts*=4,E.dts+=(A[18]&6)>>>1));E.data=A.subarray(9+A[8]);C="video"===C||E.packetLength<=r.size;if(u||C)r.size=0,r.data.length=0;C&&g.trigger("data",E)}};c.prototype.init.call(this);this.push=function(r){({pat:function(){},pes:function(){switch(r.streamType){case e.H264_STREAM_TYPE:var C=m;var u="video";break;case e.ADTS_STREAM_TYPE:C=n;u="audio";break;case e.METADATA_STREAM_TYPE:C=t;u="timed-metadata";
break;default:return}r.payloadUnitStartIndicator&&f(C,u,!0);C.data.push(r);C.size+=r.data.byteLength},pmt:function(){var C={type:"metadata",tracks:[]};h=r.programMapTable;null!==h.video&&C.tracks.push({timelineStartInfo:{baseMediaDecodeTime:0},id:+h.video,codec:"avc",type:"video"});null!==h.audio&&C.tracks.push({timelineStartInfo:{baseMediaDecodeTime:0},id:+h.audio,codec:"adts",type:"audio"});g.trigger("data",C)}})[r.type]()};this.reset=function(){m.size=0;m.data.length=0;n.size=0;n.data.length=0;
this.trigger("reset")};this.flushStreams_=function(){f(m,"video");f(n,"audio");f(t,"timed-metadata")};this.flush=function(){this.flushStreams_();this.trigger("done")}};c.prototype=new D;p={PAT_PID:0,MP2T_PACKET_LENGTH:188,TransportPacketStream:b,TransportParseStream:a,ElementaryStream:c,TimestampRolloverStream:d,CaptionStream:l.CaptionStream,Cea608Stream:l.Cea608Stream,MetadataStream:p(10)};for(var k in e)e.hasOwnProperty(k)&&(p[k]=e[k]);y.exports=p},{10:10,11:11,12:12,31:31,8:8}],10:[function(p,
y,D){D=p(31);var l=p(11),e=function(c,k,g){for(var m="";k<g;k++)m+="%"+("00"+c[k].toString(16)).slice(-2);return m},d=function(c){return c[0]<<21|c[1]<<14|c[2]<<7|c[3]},b={TXXX:function(c){var k;if(3===c.data[0]){for(k=1;k<c.data.length;k++)if(0===c.data[k]){c.description=decodeURIComponent(e(c.data,1,k));c.value=decodeURIComponent(e(c.data,k+1,c.data.length)).replace(/\0*$/,"");break}c.data=c.value}},WXXX:function(c){var k;if(3===c.data[0])for(k=1;k<c.data.length;k++)if(0===c.data[k]){c.description=
decodeURIComponent(e(c.data,1,k));c.url=decodeURIComponent(e(c.data,k+1,c.data.length));break}},PRIV:function(c){var k;for(k=0;k<c.data.length;k++)if(0===c.data[k]){c.owner=unescape(e(c.data,0,k));break}c.privateData=c.data.subarray(k+1);c.data=c.privateData}};var a=function(c){var k=!(!c||!c.debug);c=c&&c.descriptor;var g=0,m=[],n=0,t;a.prototype.init.call(this);this.dispatchType=l.METADATA_STREAM_TYPE.toString(16);if(c)for(t=0;t<c.length;t++)this.dispatchType+=("00"+c[t].toString(16)).slice(-2);
this.push=function(h){var f;if("timed-metadata"===h.type)if(h.dataAlignmentIndicator&&(n=0,m.length=0),0===m.length&&(10>h.data.length||73!==h.data[0]||68!==h.data[1]||51!==h.data[2]))k&&console.log("Skipping unrecognized metadata packet");else if(m.push(h),n+=h.data.byteLength,1===m.length&&(g=d(h.data.subarray(6,10)),g+=10),!(n<g)){h={data:new Uint8Array(g),frames:[],pts:m[0].pts,dts:m[0].dts};for(f=0;f<g;)h.data.set(m[0].data.subarray(0,g-f),f),f+=m[0].data.byteLength,n-=m[0].data.byteLength,m.shift();
f=10;h.data[5]&64&&(f=f+4+d(h.data.subarray(10,14)),g-=d(h.data.subarray(16,20)));do{var r=d(h.data.subarray(f+4,f+8));if(1>r)return console.log("Malformed ID3 frame encountered. Skipping metadata parsing.");var C=String.fromCharCode(h.data[f],h.data[f+1],h.data[f+2],h.data[f+3]);C={id:C,data:h.data.subarray(f+10,f+r+10)};C.key=C.id;if(b[C.id]&&(b[C.id](C),"com.apple.streaming.transportStreamTimestamp"===C.owner)){var u=C.data,A=(u[3]&1)<<30|u[4]<<22|u[5]<<14|u[6]<<6|u[7]>>>2;A*=4;A+=u[7]&3;C.timeStamp=
A;void 0===h.pts&&void 0===h.dts&&(h.pts=C.timeStamp,h.dts=C.timeStamp);this.trigger("timestamp",C)}h.frames.push(C);f+=10;f+=r}while(f<g);this.trigger("data",h)}}};a.prototype=new D;y.exports=a},{11:11,31:31}],11:[function(p,y,D){y.exports={H264_STREAM_TYPE:27,ADTS_STREAM_TYPE:15,METADATA_STREAM_TYPE:21}},{}],12:[function(p,y,D){p=p(31);var l=function(d,b){var a=1;for(d>b&&(a=-1);4294967296<Math.abs(b-d);)d+=8589934592*a;return d},e=function(d){var b,a;e.prototype.init.call(this);this.type_=d||"shared";
this.push=function(c){if("shared"===this.type_||c.type===this.type_)void 0===a&&(a=c.dts),c.dts=l(c.dts,a),c.pts=l(c.pts,a),b=c.dts,this.trigger("data",c)};this.flush=function(){a=b;this.trigger("done")};this.endTimeline=function(){this.flush();this.trigger("endedtimeline")};this.discontinuity=function(){b=a=void 0};this.reset=function(){this.discontinuity();this.trigger("reset")}};e.prototype=new p;y.exports={TimestampRolloverStream:e,handleRollover:l}},{31:31}],13:[function(p,y,D){var l=p(7),e=
p(29);y.exports={prefixWithSilence:function(d,b,a,c){var k,g=k=0;if(b.length){var m=e.audioTsToVideoTs(d.baseMediaDecodeTime,d.samplerate);var n=Math.ceil(e.ONE_SECOND_IN_TS/(d.samplerate/1024));a&&c&&(k=m-Math.max(a,c),k=Math.floor(k/n),g=k*n);if(!(1>k||g>e.ONE_SECOND_IN_TS/2)){a=l()[d.samplerate];a||(a=b[0].data);for(c=0;c<k;c++)m=b[0],b.splice(0,0,{data:a,dts:m.dts-n,pts:m.pts-n});d.baseMediaDecodeTime-=Math.floor(e.videoTsToAudioTs(g,d.samplerate))}}},trimAdtsFramesByEarliestDts:function(d,b,
a){if(b.minSegmentDts>=a)return d;b.minSegmentDts=Infinity;return d.filter(function(c){return c.dts>=a?(b.minSegmentDts=Math.min(b.minSegmentDts,c.dts),b.minSegmentPts=b.minSegmentDts,!0):!1})},generateSampleTable:function(d){var b,a=[];for(b=0;b<d.length;b++){var c=d[b];a.push({size:c.data.byteLength,duration:1024})}return a},concatenateFrameData:function(d){var b,a=0;var c=Uint8Array;var k=0;for(b=0;b<d.length;b++){var g=d[b];k+=g.data.byteLength}g=new c(k);for(c=0;c<d.length;c++)b=d[c],g.set(b.data,
a),a+=b.data.byteLength;return g}}},{29:29,7:7}],14:[function(p,y,D){var l=p(23).discardEmulationPreventionBytes,e=p(8).CaptionStream,d=p(15),b=p(25),a=p(27),c=p(26),k=function(m,n,t){var h=n,f=t.defaultSampleDuration||0,r=t.defaultSampleSize||0,C=t.trackId,u=[];m.forEach(function(A){A=a(A).samples;A.forEach(function(E){void 0===E.duration&&(E.duration=f);void 0===E.size&&(E.size=r);E.trackId=C;E.dts=h;void 0===E.compositionTimeOffset&&(E.compositionTimeOffset=0);E.pts=h+E.compositionTimeOffset;h+=
E.duration});u=u.concat(A)});return u},g=function(m,n){var t=d(m,["moof","traf"]),h={},f=[];d(m,["mdat"]).forEach(function(r,C){f.push({mdat:r,traf:t[C]})});f.forEach(function(r){var C=r.mdat,u=r.traf;r=d(u,["tfhd"]);var A=c(r[0]);r=A.trackId;var E=d(u,["tfdt"]);E=0<E.length?b(E[0]).baseMediaDecodeTime:0;u=d(u,["trun"]);if(n===r&&0<u.length){u=k(u,E,A);A=new DataView(C.buffer,C.byteOffset,C.byteLength);E=[];var w;for(w=0;w+4<C.length;w+=q){var q=A.getUint32(w);w+=4;if(!(0>=q))switch(C[w]&31){case 6:var z=
C.subarray(w+1,w+1+q);a:{var B=w;for(var J=0;J<u.length;J++){var G=u[J];if(B<G.size){B=G;break a}B-=G.size}B=null}z={nalUnitType:"sei_rbsp",size:q,data:z,escapedRBSP:l(z),trackId:r};if(B){z.pts=B.pts;z.dts=B.dts;var x=B}else if(x)z.pts=x.pts,z.dts=x.dts;else{console.log("We've encountered a nal unit without data. See mux.js#233.");break}E.push(z)}}h[r]||(h[r]=[]);h[r]=h[r].concat(E)}});return h};y.exports=function(){var m=!1,n,t,h,f,r,C;this.isInitialized=function(){return m};this.init=function(u){n=
new e;m=!0;C=u?u.isPartial:!1;n.on("data",function(A){A.startTime=A.startPts/f;A.endTime=A.endPts/f;r.captions.push(A);r.captionStreams[A.stream]=!0})};this.isNewInit=function(u,A){return u&&0===u.length||A&&"object"===typeof A&&0===Object.keys(A).length?!1:h!==u[0]||f!==A[h]};this.parse=function(u,A,E){if(this.isInitialized()){if(!A||!E)return null;if(this.isNewInit(A,E))h=A[0],f=E[h];else if(null===h||!f)return t.push(u),null}else return null;for(;0<t.length;){var w=t.shift();this.parse(w,A,E)}A=
h;E=f;u=null===A?null:{seiNals:g(u,A)[A],timescale:E};if(null===u||!u.seiNals)return null;this.pushNals(u.seiNals);this.flushStream();return r};this.pushNals=function(u){if(!this.isInitialized()||!u||0===u.length)return null;u.forEach(function(A){n.push(A)})};this.flushStream=function(){if(!this.isInitialized())return null;C?n.partialFlush():n.flush()};this.clearParsedCaptions=function(){r.captions=[];r.captionStreams={}};this.resetCaptionStream=function(){if(!this.isInitialized())return null;n.reset()};
this.clearAllCaptions=function(){this.clearParsedCaptions();this.resetCaptionStream()};this.reset=function(){t=[];f=h=null;r?this.clearParsedCaptions():r={captions:[],captionStreams:{}};this.resetCaptionStream()};this.reset()}},{15:15,23:23,25:25,26:26,27:27,8:8}],15:[function(p,y,D){var l=p(28).toUnsigned,e=p(19),d=function(b,a){var c=[],k;if(!a.length)return null;for(k=0;k<b.byteLength;){var g=l(b[k]<<24|b[k+1]<<16|b[k+2]<<8|b[k+3]);var m=e(b.subarray(k+4,k+8));g=1<g?k+g:b.byteLength;m===a[0]&&
(1===a.length?c.push(b.subarray(k+8,g)):(k=d(b.subarray(k+8,g),a.slice(1)),k.length&&(c=c.concat(k))));k=g}return c};y.exports=d},{19:19,28:28}],16:[function(p,y,D){var l=function(e,d){var b={size:0,flags:{isLeading:0,dependsOn:1,isDependedOn:0,hasRedundancy:0,degradationPriority:0,isNonSyncSample:1}};b.dataOffset=d;b.compositionTimeOffset=e.pts-e.dts;b.duration=e.duration;b.size=4*e.length;b.size+=e.byteLength;e.keyFrame&&(b.flags.dependsOn=2,b.flags.isNonSyncSample=0);return b};y.exports={groupNalsIntoFrames:function(e){var d,
b=[],a=[];a.byteLength=0;a.nalCount=0;a.duration=0;for(d=b.byteLength=0;d<e.length;d++){var c=e[d];"access_unit_delimiter_rbsp"===c.nalUnitType?(b.length&&(b.duration=c.dts-b.dts,a.byteLength+=b.byteLength,a.nalCount+=b.length,a.duration+=b.duration,a.push(b)),b=[c],b.byteLength=c.data.byteLength,b.pts=c.pts,b.dts=c.dts):("slice_layer_without_partitioning_rbsp_idr"===c.nalUnitType&&(b.keyFrame=!0),b.duration=c.dts-b.dts,b.byteLength+=c.data.byteLength,b.push(c))}a.length&&(!b.duration||0>=b.duration)&&
(b.duration=a[a.length-1].duration);a.byteLength+=b.byteLength;a.nalCount+=b.length;a.duration+=b.duration;a.push(b);return a},groupFramesIntoGops:function(e){var d,b=[],a=[];b.byteLength=0;b.nalCount=0;b.duration=0;b.pts=e[0].pts;b.dts=e[0].dts;a.byteLength=0;a.nalCount=0;a.duration=0;a.pts=e[0].pts;a.dts=e[0].dts;for(d=0;d<e.length;d++){var c=e[d];c.keyFrame?(b.length&&(a.push(b),a.byteLength+=b.byteLength,a.nalCount+=b.nalCount,a.duration+=b.duration),b=[c],b.nalCount=c.length,b.byteLength=c.byteLength,
b.pts=c.pts,b.dts=c.dts,b.duration=c.duration):(b.duration+=c.duration,b.nalCount+=c.length,b.byteLength+=c.byteLength,b.push(c))}a.length&&0>=b.duration&&(b.duration=a[a.length-1].duration);a.byteLength+=b.byteLength;a.nalCount+=b.nalCount;a.duration+=b.duration;a.push(b);return a},extendFirstKeyFrame:function(e){if(!e[0][0].keyFrame&&1<e.length){var d=e.shift();e.byteLength-=d.byteLength;e.nalCount-=d.nalCount;e[0][0].dts=d.dts;e[0][0].pts=d.pts;e[0][0].duration+=d.duration}return e},generateSampleTable:function(e,
d){var b,a,c=d||0,k=[];for(b=0;b<e.length;b++){var g=e[b];for(a=0;a<g.length;a++){var m=g[a];m=l(m,c);c+=m.size;k.push(m)}}return k},concatenateNalData:function(e){var d,b,a,c=0,k=new Uint8Array(e.byteLength+4*e.nalCount),g=new DataView(k.buffer);for(d=0;d<e.length;d++){var m=e[d];for(b=0;b<m.length;b++){var n=m[b];for(a=0;a<n.length;a++){var t=n[a];g.setUint32(c,t.data.byteLength);c+=4;k.set(t.data,c);c+=t.data.byteLength}}}return k},generateSampleTableForFrame:function(e,d){var b=[];var a=l(e,d||
0);b.push(a);return b},concatenateNalDataForFrame:function(e){var d,b=0,a=new Uint8Array(e.byteLength+4*e.length),c=new DataView(a.buffer);for(d=0;d<e.length;d++){var k=e[d];c.setUint32(b,k.data.byteLength);b+=4;a.set(k.data,b);b+=k.data.byteLength}return a}}},{}],17:[function(p,y,D){y.exports={generator:p(18),probe:p(20),Transmuxer:p(22).Transmuxer,AudioSegmentStream:p(22).AudioSegmentStream,VideoSegmentStream:p(22).VideoSegmentStream,CaptionParser:p(14)}},{14:14,18:18,20:20,22:22}],18:[function(p,
y,D){var l=Math.pow(2,32)-1,e,d,b,a,c,k,g,m,n,t,h,f,r,C,u,A,E=4294967295;(function(){var v;b={avc1:[],avcC:[],btrt:[],dinf:[],dref:[],esds:[],ftyp:[],hdlr:[],mdat:[],mdhd:[],mdia:[],mfhd:[],minf:[],moof:[],moov:[],mp4a:[],mvex:[],mvhd:[],pasp:[],sdtp:[],smhd:[],stbl:[],stco:[],stsc:[],stsd:[],stsz:[],stts:[],styp:[],tfdt:[],tfhd:[],traf:[],trak:[],trun:[],trex:[],tkhd:[],vmhd:[]};if("undefined"!==typeof Uint8Array){for(v in b)b.hasOwnProperty(v)&&(b[v]=[v.charCodeAt(0),v.charCodeAt(1),v.charCodeAt(2),
v.charCodeAt(3)]);a=new Uint8Array([105,115,111,109]);k=new Uint8Array([97,118,99,49]);c=new Uint8Array([0,0,0,1]);g=new Uint8Array([0,0,0,0,0,0,0,0,118,105,100,101,0,0,0,0,0,0,0,0,0,0,0,0,86,105,100,101,111,72,97,110,100,108,101,114,0]);m=new Uint8Array([0,0,0,0,0,0,0,0,115,111,117,110,0,0,0,0,0,0,0,0,0,0,0,0,83,111,117,110,100,72,97,110,100,108,101,114,0]);n={video:g,audio:m};f=new Uint8Array([0,0,0,0,0,0,0,1,0,0,0,12,117,114,108,32,0,0,0,1]);h=new Uint8Array([0,0,0,0,0,0,0,0]);C=r=new Uint8Array([0,
0,0,0,0,0,0,0]);u=new Uint8Array([0,0,0,0,0,0,0,0,0,0,0,0]);A=r;t=new Uint8Array([0,0,0,1,0,0,0,0,0,0,0,0])}})();var w=function(v){var N=[],I=0,K;for(K=1;K<arguments.length;K++)N.push(arguments[K]);for(K=N.length;K--;)I+=N[K].byteLength;var Q=new Uint8Array(I+8);(new DataView(Q.buffer,Q.byteOffset,Q.byteLength)).setUint32(0,Q.byteLength);Q.set(v,4);K=0;for(I=8;K<N.length;K++)Q.set(N[K],I),I+=N[K].byteLength;return Q};var q=function(){return w(b.dinf,w(b.dref,f))};var z=function(v){return w(b.esds,
new Uint8Array([0,0,0,0,3,25,0,0,0,4,17,64,21,0,6,0,0,0,218,192,0,0,218,192,5,2,v.audioobjecttype<<3|v.samplingfrequencyindex>>>1,v.samplingfrequencyindex<<7|v.channelcount<<3,6,1,2]))};var B=function(){return w(b.ftyp,a,c,a,k)};var J=function(v){return w(b.hdlr,n[v])};var G=function(v){var N=new Uint8Array([0,0,0,0,0,0,0,2,0,0,0,3,0,1,95,144,v.duration>>>24&255,v.duration>>>16&255,v.duration>>>8&255,v.duration&255,85,196,0,0]);v.samplerate&&(N[12]=v.samplerate>>>24&255,N[13]=v.samplerate>>>16&255,
N[14]=v.samplerate>>>8&255,N[15]=v.samplerate&255,v.duration=v.duration/9E4*v.samplerate,N[16]=v.duration>>>24&255,N[17]=v.duration>>>16&255,N[18]=v.duration>>>8&255,N[19]=v.duration&255);return w(b.mdhd,N)};var x=function(v){return w(b.mdia,G(v),J(v.type),F(v))};var H=function(v){return w(b.mfhd,new Uint8Array([0,0,0,0,(v&4278190080)>>24,(v&16711680)>>16,(v&65280)>>8,v&255]))};var F=function(v){return w(b.minf,"video"===v.type?w(b.vmhd,t):w(b.smhd,h),q(),W(v))};var P=function(v){for(var N=v.length,
I=[];N--;)I[N]=Z(v[N]);return w.apply(null,[b.moov,T(E)].concat(I).concat(O(v)))};var O=function(v){for(var N=v.length,I=[];N--;)I[N]=aa(v[N]);return w.apply(null,[b.mvex].concat(I))};var T=function(v){v=new Uint8Array([0,0,0,0,0,0,0,1,0,0,0,2,0,1,95,144,(v&4278190080)>>24,(v&16711680)>>16,(v&65280)>>8,v&255,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,255,255]);return w(b.mvhd,v)};
var L=function(v){v=v.samples||[];var N=new Uint8Array(4+v.length),I;for(I=0;I<v.length;I++){var K=v[I].flags;N[I+4]=K.dependsOn<<4|K.isDependedOn<<2|K.hasRedundancy}return w(b.sdtp,N)};var W=function(v){return w(b.stbl,e(v),w(b.stts,A),w(b.stsc,C),w(b.stsz,u),w(b.stco,r))};(function(){e=function(I){return w(b.stsd,new Uint8Array([0,0,0,0,0,0,0,1]),"video"===I.type?v(I):N(I))};var v=function(I){var K=I.sps||[],Q=I.pps||[],V=[],U=[],M;for(M=0;M<K.length;M++)V.push((K[M].byteLength&65280)>>>8),V.push(K[M].byteLength&
255),V=V.concat(Array.prototype.slice.call(K[M]));for(M=0;M<Q.length;M++)U.push((Q[M].byteLength&65280)>>>8),U.push(Q[M].byteLength&255),U=U.concat(Array.prototype.slice.call(Q[M]));K=[b.avc1,new Uint8Array([0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,(I.width&65280)>>8,I.width&255,(I.height&65280)>>8,I.height&255,0,72,0,0,0,72,0,0,0,0,0,0,0,1,19,118,105,100,101,111,106,115,45,99,111,110,116,114,105,98,45,104,108,115,0,0,0,0,0,0,0,0,0,0,0,0,0,24,17,17]),w(b.avcC,new Uint8Array([1,I.profileIdc,
I.profileCompatibility,I.levelIdc,255].concat([K.length],V,[Q.length],U))),w(b.btrt,new Uint8Array([0,28,156,128,0,45,198,192,0,45,198,192]))];I.sarRatio&&(Q=I.sarRatio[0],I=I.sarRatio[1],K.push(w(b.pasp,new Uint8Array([(Q&4278190080)>>24,(Q&16711680)>>16,(Q&65280)>>8,Q&255,(I&4278190080)>>24,(I&16711680)>>16,(I&65280)>>8,I&255]))));return w.apply(null,K)};var N=function(I){return w(b.mp4a,new Uint8Array([0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,(I.channelcount&65280)>>8,I.channelcount&255,(I.samplesize&65280)>>
8,I.samplesize&255,0,0,0,0,(I.samplerate&65280)>>8,I.samplerate&255,0,0]),z(I))}})();var Y=function(v){v=new Uint8Array([0,0,0,7,0,0,0,0,0,0,0,0,(v.id&4278190080)>>24,(v.id&16711680)>>16,(v.id&65280)>>8,v.id&255,0,0,0,0,(v.duration&4278190080)>>24,(v.duration&16711680)>>16,(v.duration&65280)>>8,v.duration&255,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,0,0,0,(v.width&65280)>>8,v.width&255,0,0,(v.height&65280)>>8,v.height&255,0,0]);return w(b.tkhd,
v)};var X=function(v){var N=w(b.tfhd,new Uint8Array([0,0,0,58,(v.id&4278190080)>>24,(v.id&16711680)>>16,(v.id&65280)>>8,v.id&255,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0]));var I=Math.floor(v.baseMediaDecodeTime/(l+1));var K=Math.floor(v.baseMediaDecodeTime%(l+1));I=w(b.tfdt,new Uint8Array([1,0,0,0,I>>>24&255,I>>>16&255,I>>>8&255,I&255,K>>>24&255,K>>>16&255,K>>>8&255,K&255]));if("audio"===v.type)return v=d(v,92),w(b.traf,N,I,v);K=L(v);v=d(v,K.length+92);return w(b.traf,N,I,v,K)};var Z=function(v){v.duration=
v.duration||E;return w(b.trak,Y(v),x(v))};var aa=function(v){var N=new Uint8Array([0,0,0,0,(v.id&4278190080)>>24,(v.id&16711680)>>16,(v.id&65280)>>8,v.id&255,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,1]);"video"!==v.type&&(N[N.length-1]=0);return w(b.trex,N)};(function(){var v=function(K,Q){var V=0,U=0,M=0,R=0;K.length&&(void 0!==K[0].duration&&(V=1),void 0!==K[0].size&&(U=2),void 0!==K[0].flags&&(M=4),void 0!==K[0].compositionTimeOffset&&(R=8));return[0,0,V|U|M|R,1,(K.length&4278190080)>>>24,(K.length&16711680)>>>
16,(K.length&65280)>>>8,K.length&255,(Q&4278190080)>>>24,(Q&16711680)>>>16,(Q&65280)>>>8,Q&255]};var N=function(K,Q){var V;var U=K.samples||[];Q+=20+16*U.length;var M=v(U,Q);var R=new Uint8Array(M.length+16*U.length);R.set(M);M=M.length;for(V=0;V<U.length;V++){var S=U[V];R[M++]=(S.duration&4278190080)>>>24;R[M++]=(S.duration&16711680)>>>16;R[M++]=(S.duration&65280)>>>8;R[M++]=S.duration&255;R[M++]=(S.size&4278190080)>>>24;R[M++]=(S.size&16711680)>>>16;R[M++]=(S.size&65280)>>>8;R[M++]=S.size&255;R[M++]=
S.flags.isLeading<<2|S.flags.dependsOn;R[M++]=S.flags.isDependedOn<<6|S.flags.hasRedundancy<<4|S.flags.paddingValue<<1|S.flags.isNonSyncSample;R[M++]=S.flags.degradationPriority&61440;R[M++]=S.flags.degradationPriority&15;R[M++]=(S.compositionTimeOffset&4278190080)>>>24;R[M++]=(S.compositionTimeOffset&16711680)>>>16;R[M++]=(S.compositionTimeOffset&65280)>>>8;R[M++]=S.compositionTimeOffset&255}return w(b.trun,R)};var I=function(K,Q){var V;var U=K.samples||[];Q+=20+8*U.length;var M=v(U,Q);var R=new Uint8Array(M.length+
8*U.length);R.set(M);M=M.length;for(V=0;V<U.length;V++){var S=U[V];R[M++]=(S.duration&4278190080)>>>24;R[M++]=(S.duration&16711680)>>>16;R[M++]=(S.duration&65280)>>>8;R[M++]=S.duration&255;R[M++]=(S.size&4278190080)>>>24;R[M++]=(S.size&16711680)>>>16;R[M++]=(S.size&65280)>>>8;R[M++]=S.size&255}return w(b.trun,R)};d=function(K,Q){return"audio"===K.type?I(K,Q):N(K,Q)}})();y.exports={ftyp:B,mdat:function(v){return w(b.mdat,v)},moof:function(v,N){for(var I=[],K=N.length;K--;)I[K]=X(N[K]);return w.apply(null,
[b.moof,H(v)].concat(I))},moov:P,setDuration:function(v){v&&(E=9E4*v)},initSegment:function(v){var N=B();v=P(v);var I=new Uint8Array(N.byteLength+v.byteLength);I.set(N);I.set(v,N.byteLength);return I}}},{}],19:[function(p,y,D){y.exports=function(l){var e=""+String.fromCharCode(l[0]);e+=String.fromCharCode(l[1]);e+=String.fromCharCode(l[2]);return e+=String.fromCharCode(l[3])}},{}],20:[function(p,y,D){var l=p(28).toUnsigned,e=p(28).toHexString,d=p(15),b=p(19),a=p(26),c=p(27),k=p(25);var g=function(m){var n=
0===m[0]?12:20;return l(m[n]<<24|m[n+1]<<16|m[n+2]<<8|m[n+3])};y.exports={findBox:d,parseType:b,timescale:function(m){return d(m,["moov","trak"]).reduce(function(n,t){var h=d(t,["tkhd"])[0];if(!h)return null;var f=h[0];f=0===f?12:20;h=l(h[f]<<24|h[f+1]<<16|h[f+2]<<8|h[f+3]);var r=d(t,["mdia","mdhd"])[0];if(!r)return null;f=r[0];f=0===f?12:20;n[h]=l(r[f]<<24|r[f+1]<<16|r[f+2]<<8|r[f+3]);return n},{})},startTime:function(m,n){var t=d(n,["moof","traf"]);t=[].concat.apply([],t.map(function(h){return d(h,
["tfhd"]).map(function(f){f=l(f[4]<<24|f[5]<<16|f[6]<<8|f[7]);f=m[f]||9E4;var r=(r=d(h,["tfdt"]).map(function(C){var u=C[0];var A=l(C[4]<<24|C[5]<<16|C[6]<<8|C[7]);1===u&&(A*=Math.pow(2,32),A+=l(C[8]<<24|C[9]<<16|C[10]<<8|C[11]));return A})[0])||Infinity;return r/f})}));t=Math.min.apply(null,t);return isFinite(t)?t:0},compositionStartTime:function(m,n){var t=d(n,["moof","traf"]),h=0,f=0;if(t&&t.length){var r=d(t[0],["tfhd"])[0],C=d(t[0],["trun"])[0];t=d(t[0],["tfdt"])[0];if(r)var u=a(r).trackId;t&&
(h=k(t).baseMediaDecodeTime);C&&(r=c(C),r.samples&&r.samples.length&&(f=r.samples[0].compositionTimeOffset||0))}return(h+f)/(m[u]||9E4)},videoTrackIds:function(m){var n=[];d(m,["moov","trak"]).forEach(function(t){var h=d(t,["mdia","hdlr"]),f=d(t,["tkhd"]);h.forEach(function(r,C){var u=b(r.subarray(8,12)),A=f[C];"vide"===u&&(u=new DataView(A.buffer,A.byteOffset,A.byteLength),A=u.getUint8(0),u=0===A?u.getUint32(12):u.getUint32(20),n.push(u))})});return n},tracks:function(m){var n=[];d(m,["moov","trak"]).forEach(function(t){var h=
{},f=d(t,["tkhd"])[0];if(f){f=new DataView(f.buffer,f.byteOffset,f.byteLength);var r=f.getUint8(0);h.id=0===r?f.getUint32(12):f.getUint32(20)}if(f=d(t,["mdia","hdlr"])[0])f=b(f.subarray(8,12)),h.type="vide"===f?"video":"soun"===f?"audio":f;if(f=d(t,["mdia","minf","stbl","stsd"])[0])if(f=f.subarray(8),h.codec=b(f.subarray(4,8)),f=d(f,[h.codec])[0])/^[a-z]vc[1-9]$/i.test(h.codec)?(f=f.subarray(78),r=b(f.subarray(4,8)),"avcC"===r&&11<f.length?(h.codec+=".",h.codec+=e(f[9]),h.codec+=e(f[10]),h.codec+=
e(f[11])):h.codec="avc1.4d400d"):/^mp4[a,v]$/i.test(h.codec)&&(f=f.subarray(28),r=b(f.subarray(4,8)),"esds"===r&&20<f.length&&0!==f[19]?(h.codec+="."+e(f[19]),h.codec+="."+e(f[20]>>>2&63).replace(/^0/,"")):h.codec="mp4a.40.2");if(t=d(t,["mdia","mdhd"])[0])h.timescale=g(t);n.push(h)});return n},getTimescaleFromMediaHeader:g}},{15:15,19:19,25:25,26:26,27:27,28:28}],21:[function(p,y,D){var l=p(29).ONE_SECOND_IN_TS;y.exports={clearDtsInfo:function(e){delete e.minSegmentDts;delete e.maxSegmentDts;delete e.minSegmentPts;
delete e.maxSegmentPts},calculateTrackBaseMediaDecodeTime:function(e,d){var b=e.minSegmentDts;d||(b-=e.timelineStartInfo.dts);var a=e.timelineStartInfo.baseMediaDecodeTime;a=Math.max(0,a+b);"audio"===e.type&&(b=e.samplerate/l,a=Math.floor(a*b));return a},collectDtsInfo:function(e,d){"number"===typeof d.pts&&(void 0===e.timelineStartInfo.pts&&(e.timelineStartInfo.pts=d.pts),e.minSegmentPts=void 0===e.minSegmentPts?d.pts:Math.min(e.minSegmentPts,d.pts),e.maxSegmentPts=void 0===e.maxSegmentPts?d.pts:
Math.max(e.maxSegmentPts,d.pts));"number"===typeof d.dts&&(void 0===e.timelineStartInfo.dts&&(e.timelineStartInfo.dts=d.dts),e.minSegmentDts=void 0===e.minSegmentDts?d.dts:Math.min(e.minSegmentDts,d.dts),e.maxSegmentDts=void 0===e.maxSegmentDts?d.dts:Math.max(e.maxSegmentDts,d.dts))}}},{29:29}],22:[function(p,y,D){D=p(31);var l=p(18),e=p(16),d=p(13),b=p(21),a=p(9),c=p(29),k=p(3),g=p(4).H264Stream,m=p(1),n=p(2).isLikelyAacData,t=p(29).ONE_SECOND_IN_TS,h=p(5),f=p(6),r=function(q,z){var B;if(q.length!==
z.length)return!1;for(B=0;B<q.length;B++)if(q[B]!==z[B])return!1;return!0},C=function(q,z,B,J,G,x){return{start:{dts:q,pts:q+(B-z)},end:{dts:q+(J-z),pts:q+(G-B)},prependedContentDuration:x,baseMediaDecodeTime:q}};var u=function(q,z){var B=[],J=0,G=0,x=0,H=Infinity;z=z||{};u.prototype.init.call(this);this.push=function(F){b.collectDtsInfo(q,F);q&&h.forEach(function(P){q[P]=F[P]});B.push(F)};this.setEarliestDts=function(F){G=F};this.setVideoBaseMediaDecodeTime=function(F){H=F};this.setAudioAppendStart=
function(F){x=F};this.flush=function(){if(0!==B.length){var F=d.trimAdtsFramesByEarliestDts(B,q,G);q.baseMediaDecodeTime=b.calculateTrackBaseMediaDecodeTime(q,z.keepOriginalTimestamps);d.prefixWithSilence(q,F,x,H);q.samples=d.generateSampleTable(F);var P=l.mdat(d.concatenateFrameData(F));B=[];var O=l.moof(J,[q]);var T=new Uint8Array(O.byteLength+P.byteLength);J++;T.set(O);T.set(P,O.byteLength);b.clearDtsInfo(q);O=Math.ceil(1024*t/q.samplerate);F.length&&this.trigger("timingInfo",{start:F[0].pts,end:F[0].pts+
F.length*O});this.trigger("data",{track:q,boxes:T})}this.trigger("done","AudioSegmentStream")};this.reset=function(){b.clearDtsInfo(q);B=[];this.trigger("reset")}};u.prototype=new D;var A=function(q,z){var B=0,J=[],G=[],x,H;z=z||{};A.prototype.init.call(this);delete q.minPTS;this.gopCache_=[];this.push=function(F){b.collectDtsInfo(q,F);"seq_parameter_set_rbsp"!==F.nalUnitType||x||(x=F.config,q.sps=[F.data],f.forEach(function(P){q[P]=x[P]},this));"pic_parameter_set_rbsp"!==F.nalUnitType||H||(H=F.data,
q.pps=[F.data]);J.push(F)};this.flush=function(){var F;var P=0;for(var O,T;J.length&&"access_unit_delimiter_rbsp"!==J[0].nalUnitType;)J.shift();if(0!==J.length){var L=e.groupNalsIntoFrames(J);L=e.groupFramesIntoGops(L);L[0][0].keyFrame||((F=this.getGopForFusion_(J[0],q))?(P=F.duration,L.unshift(F),L.byteLength+=F.byteLength,L.nalCount+=F.nalCount,L.pts=F.pts,L.dts=F.dts,L.duration+=F.duration):L=e.extendFirstKeyFrame(L));if(G.length){F=z.alignGopsAtEnd?this.alignGopsAtEnd_(L):this.alignGopsAtStart_(L);
if(!F){this.gopCache_.unshift({gop:L.pop(),pps:q.pps,sps:q.sps});this.gopCache_.length=Math.min(6,this.gopCache_.length);J=[];this.resetStream_();this.trigger("done","VideoSegmentStream");return}b.clearDtsInfo(q);L=F}b.collectDtsInfo(q,L);q.samples=e.generateSampleTable(L);F=l.mdat(e.concatenateNalData(L));q.baseMediaDecodeTime=b.calculateTrackBaseMediaDecodeTime(q,z.keepOriginalTimestamps);this.trigger("processedGopsInfo",L.map(function(W){return{pts:W.pts,dts:W.dts,byteLength:W.byteLength}}));O=
L[0];T=L[L.length-1];this.trigger("segmentTimingInfo",C(q.baseMediaDecodeTime,O.dts,O.pts,T.dts+T.duration,T.pts+T.duration,P));this.trigger("timingInfo",{start:L[0].pts,end:L[L.length-1].pts+L[L.length-1].duration});this.gopCache_.unshift({gop:L.pop(),pps:q.pps,sps:q.sps});this.gopCache_.length=Math.min(6,this.gopCache_.length);J=[];this.trigger("baseMediaDecodeTime",q.baseMediaDecodeTime);this.trigger("timelineStartInfo",q.timelineStartInfo);P=l.moof(B,[q]);L=new Uint8Array(P.byteLength+F.byteLength);
B++;L.set(P);L.set(F,P.byteLength);this.trigger("data",{track:q,boxes:L})}this.resetStream_();this.trigger("done","VideoSegmentStream")};this.reset=function(){this.resetStream_();J=[];this.gopCache_.length=0;G.length=0;this.trigger("reset")};this.resetStream_=function(){b.clearDtsInfo(q);H=x=void 0};this.getGopForFusion_=function(F){var P=Infinity,O;for(O=0;O<this.gopCache_.length;O++){var T=this.gopCache_[O];var L=T.gop;if(q.pps&&r(q.pps[0],T.pps[0])&&q.sps&&r(q.sps[0],T.sps[0])&&!(L.dts<q.timelineStartInfo.dts)&&
(L=F.dts-L.dts-L.duration,-1E4<=L&&45E3>=L&&(!W||P>L))){var W=T;P=L}}return W?W.gop:null};this.alignGopsAtStart_=function(F){var P,O;var T=F.byteLength;var L=F.nalCount;var W=F.duration;for(P=O=0;P<G.length&&O<F.length;){var Y=G[P];var X=F[O];if(Y.pts===X.pts)break;X.pts>Y.pts?P++:(O++,T-=X.byteLength,L-=X.nalCount,W-=X.duration)}if(0===O)return F;if(O===F.length)return null;F=F.slice(O);F.byteLength=T;F.duration=W;F.nalCount=L;F.pts=F[0].pts;F.dts=F[0].dts;return F};this.alignGopsAtEnd_=function(F){var P;
var O=G.length-1;var T=F.length-1;var L=null;for(P=!1;0<=O&&0<=T;){var W=G[O];var Y=F[T];if(W.pts===Y.pts){P=!0;break}W.pts>Y.pts?O--:(O===G.length-1&&(L=T),T--)}if(!P&&null===L)return null;O=P?T:L;if(0===O)return F;F=F.slice(O);O=F.reduce(function(X,Z){X.byteLength+=Z.byteLength;X.duration+=Z.duration;X.nalCount+=Z.nalCount;return X},{byteLength:0,duration:0,nalCount:0});F.byteLength=O.byteLength;F.duration=O.duration;F.nalCount=O.nalCount;F.pts=F[0].pts;F.dts=F[0].dts;return F};this.alignGopsWith=
function(F){G=F}};A.prototype=new D;var E=function(q,z){this.numberOfTracks=0;this.metadataStream=z;q=q||{};this.remuxTracks="undefined"!==typeof q.remux?!!q.remux:!0;this.keepOriginalTimestamps="boolean"===typeof q.keepOriginalTimestamps?q.keepOriginalTimestamps:!1;this.pendingTracks=[];this.videoTrack=null;this.pendingBoxes=[];this.pendingCaptions=[];this.pendingMetadata=[];this.emittedTracks=this.pendingBytes=0;E.prototype.init.call(this);this.push=function(B){if(B.text)return this.pendingCaptions.push(B);
if(B.frames)return this.pendingMetadata.push(B);this.pendingTracks.push(B.track);this.pendingBytes+=B.boxes.byteLength;"video"===B.track.type&&(this.videoTrack=B.track,this.pendingBoxes.push(B.boxes));"audio"===B.track.type&&(this.audioTrack=B.track,this.pendingBoxes.unshift(B.boxes))}};E.prototype=new D;E.prototype.flush=function(q){var z=0,B={captions:[],captionStreams:{},metadata:[],info:{}},J=0;if(this.pendingTracks.length<this.numberOfTracks){if("VideoSegmentStream"!==q&&"AudioSegmentStream"!==
q||this.remuxTracks)return;if(0===this.pendingTracks.length){this.emittedTracks++;this.emittedTracks>=this.numberOfTracks&&(this.trigger("done"),this.emittedTracks=0);return}}this.videoTrack?(J=this.videoTrack.timelineStartInfo.pts,f.forEach(function(G){B.info[G]=this.videoTrack[G]},this)):this.audioTrack&&(J=this.audioTrack.timelineStartInfo.pts,h.forEach(function(G){B.info[G]=this.audioTrack[G]},this));if(this.videoTrack||this.audioTrack){B.type=1===this.pendingTracks.length?this.pendingTracks[0].type:
"combined";this.emittedTracks+=this.pendingTracks.length;q=l.initSegment(this.pendingTracks);B.initSegment=new Uint8Array(q.byteLength);B.initSegment.set(q);B.data=new Uint8Array(this.pendingBytes);for(q=0;q<this.pendingBoxes.length;q++)B.data.set(this.pendingBoxes[q],z),z+=this.pendingBoxes[q].byteLength;for(q=0;q<this.pendingCaptions.length;q++)z=this.pendingCaptions[q],z.startTime=c.metadataTsToSeconds(z.startPts,J,this.keepOriginalTimestamps),z.endTime=c.metadataTsToSeconds(z.endPts,J,this.keepOriginalTimestamps),
B.captionStreams[z.stream]=!0,B.captions.push(z);for(q=0;q<this.pendingMetadata.length;q++)z=this.pendingMetadata[q],z.cueTime=c.metadataTsToSeconds(z.pts,J,this.keepOriginalTimestamps),B.metadata.push(z);B.metadata.dispatchType=this.metadataStream.dispatchType;this.pendingTracks.length=0;this.videoTrack=null;this.pendingBoxes.length=0;this.pendingBytes=this.pendingCaptions.length=0;this.pendingMetadata.length=0;this.trigger("data",B);for(q=0;q<B.captions.length;q++)z=B.captions[q],this.trigger("caption",
z);for(q=0;q<B.metadata.length;q++)z=B.metadata[q],this.trigger("id3Frame",z)}this.emittedTracks>=this.numberOfTracks&&(this.trigger("done"),this.emittedTracks=0)};E.prototype.setRemux=function(q){this.remuxTracks=q};var w=function(q){var z=this,B=!0,J,G;w.prototype.init.call(this);q=q||{};this.baseMediaDecodeTime=q.baseMediaDecodeTime||0;this.transmuxPipeline_={};l.setDuration(q.duration);this.setupAacPipeline=function(){var x={};this.transmuxPipeline_=x;x.type="aac";x.metadataStream=new a.MetadataStream;
x.aacStream=new m;x.audioTimestampRolloverStream=new a.TimestampRolloverStream("audio");x.timedMetadataTimestampRolloverStream=new a.TimestampRolloverStream("timed-metadata");x.adtsStream=new k;x.coalesceStream=new E(q,x.metadataStream);x.headOfPipeline=x.aacStream;x.aacStream.pipe(x.audioTimestampRolloverStream).pipe(x.adtsStream);x.aacStream.pipe(x.timedMetadataTimestampRolloverStream).pipe(x.metadataStream).pipe(x.coalesceStream);x.metadataStream.on("timestamp",function(H){x.aacStream.setTimestamp(H.timeStamp)});
x.aacStream.on("data",function(H){"timed-metadata"!==H.type&&"audio"!==H.type||x.audioSegmentStream||(G=G||{timelineStartInfo:{baseMediaDecodeTime:z.baseMediaDecodeTime},codec:"adts",type:"audio"},x.coalesceStream.numberOfTracks++,x.audioSegmentStream=new u(G,q),x.audioSegmentStream.on("timingInfo",z.trigger.bind(z,"audioTimingInfo")),x.adtsStream.pipe(x.audioSegmentStream).pipe(x.coalesceStream),z.trigger("trackinfo",{hasAudio:!!G,hasVideo:!!J}))});x.coalesceStream.on("data",this.trigger.bind(this,
"data"));x.coalesceStream.on("done",this.trigger.bind(this,"done"))};this.setupTsPipeline=function(){var x={};this.transmuxPipeline_=x;x.type="ts";x.metadataStream=new a.MetadataStream;x.packetStream=new a.TransportPacketStream;x.parseStream=new a.TransportParseStream;x.elementaryStream=new a.ElementaryStream;x.timestampRolloverStream=new a.TimestampRolloverStream;x.adtsStream=new k;x.h264Stream=new g;x.captionStream=new a.CaptionStream;x.coalesceStream=new E(q,x.metadataStream);x.headOfPipeline=
x.packetStream;x.packetStream.pipe(x.parseStream).pipe(x.elementaryStream).pipe(x.timestampRolloverStream);x.timestampRolloverStream.pipe(x.h264Stream);x.timestampRolloverStream.pipe(x.adtsStream);x.timestampRolloverStream.pipe(x.metadataStream).pipe(x.coalesceStream);x.h264Stream.pipe(x.captionStream).pipe(x.coalesceStream);x.elementaryStream.on("data",function(H){var F;if("metadata"===H.type){for(F=H.tracks.length;F--;)J||"video"!==H.tracks[F].type?G||"audio"!==H.tracks[F].type||(G=H.tracks[F],
G.timelineStartInfo.baseMediaDecodeTime=z.baseMediaDecodeTime):(J=H.tracks[F],J.timelineStartInfo.baseMediaDecodeTime=z.baseMediaDecodeTime);J&&!x.videoSegmentStream&&(x.coalesceStream.numberOfTracks++,x.videoSegmentStream=new A(J,q),x.videoSegmentStream.on("timelineStartInfo",function(P){G&&!q.keepOriginalTimestamps&&(G.timelineStartInfo=P,x.audioSegmentStream.setEarliestDts(P.dts-z.baseMediaDecodeTime))}),x.videoSegmentStream.on("processedGopsInfo",z.trigger.bind(z,"gopInfo")),x.videoSegmentStream.on("segmentTimingInfo",
z.trigger.bind(z,"videoSegmentTimingInfo")),x.videoSegmentStream.on("baseMediaDecodeTime",function(P){G&&x.audioSegmentStream.setVideoBaseMediaDecodeTime(P)}),x.videoSegmentStream.on("timingInfo",z.trigger.bind(z,"videoTimingInfo")),x.h264Stream.pipe(x.videoSegmentStream).pipe(x.coalesceStream));G&&!x.audioSegmentStream&&(x.coalesceStream.numberOfTracks++,x.audioSegmentStream=new u(G,q),x.audioSegmentStream.on("timingInfo",z.trigger.bind(z,"audioTimingInfo")),x.adtsStream.pipe(x.audioSegmentStream).pipe(x.coalesceStream));
z.trigger("trackinfo",{hasAudio:!!G,hasVideo:!!J})}});x.coalesceStream.on("data",this.trigger.bind(this,"data"));x.coalesceStream.on("id3Frame",function(H){H.dispatchType=x.metadataStream.dispatchType;z.trigger("id3Frame",H)});x.coalesceStream.on("caption",this.trigger.bind(this,"caption"));x.coalesceStream.on("done",this.trigger.bind(this,"done"))};this.setBaseMediaDecodeTime=function(x){var H=this.transmuxPipeline_;q.keepOriginalTimestamps||(this.baseMediaDecodeTime=x);G&&(G.timelineStartInfo.dts=
void 0,G.timelineStartInfo.pts=void 0,b.clearDtsInfo(G),H.audioTimestampRolloverStream&&H.audioTimestampRolloverStream.discontinuity());J&&(H.videoSegmentStream&&(H.videoSegmentStream.gopCache_=[]),J.timelineStartInfo.dts=void 0,J.timelineStartInfo.pts=void 0,b.clearDtsInfo(J),H.captionStream.reset());H.timestampRolloverStream&&H.timestampRolloverStream.discontinuity()};this.setAudioAppendStart=function(x){G&&this.transmuxPipeline_.audioSegmentStream.setAudioAppendStart(x)};this.setRemux=function(x){var H=
this.transmuxPipeline_;q.remux=x;H&&H.coalesceStream&&H.coalesceStream.setRemux(x)};this.alignGopsWith=function(x){J&&this.transmuxPipeline_.videoSegmentStream&&this.transmuxPipeline_.videoSegmentStream.alignGopsWith(x)};this.push=function(x){if(B){var H=n(x);H&&"aac"!==this.transmuxPipeline_.type?this.setupAacPipeline():H||"ts"===this.transmuxPipeline_.type||this.setupTsPipeline();B=!1}this.transmuxPipeline_.headOfPipeline.push(x)};this.flush=function(){B=!0;this.transmuxPipeline_.headOfPipeline.flush()};
this.endTimeline=function(){this.transmuxPipeline_.headOfPipeline.endTimeline()};this.reset=function(){this.transmuxPipeline_.headOfPipeline&&this.transmuxPipeline_.headOfPipeline.reset()};this.resetCaptions=function(){this.transmuxPipeline_.captionStream&&this.transmuxPipeline_.captionStream.reset()}};w.prototype=new D;y.exports={Transmuxer:w,VideoSegmentStream:A,AudioSegmentStream:u,AUDIO_PROPERTIES:h,VIDEO_PROPERTIES:f,generateVideoSegmentTimingInfo:C}},{1:1,13:13,16:16,18:18,2:2,21:21,29:29,3:3,
31:31,4:4,5:5,6:6,9:9}],23:[function(p,y,D){y.exports={parseSei:function(l){for(var e=0,d={payloadType:-1,payloadSize:0},b=0,a=0;e<l.byteLength&&128!==l[e];){for(;255===l[e];)b+=255,e++;for(b+=l[e++];255===l[e];)a+=255,e++;a+=l[e++];if(!d.payload&&4===b)if("GA94"===String.fromCharCode(l[e+3],l[e+4],l[e+5],l[e+6])){d.payloadType=b;d.payloadSize=a;d.payload=l.subarray(e,e+a);break}else d.payload=void 0;e+=a;a=b=0}return d},parseUserData:function(l){return 181!==l.payload[0]||49!==(l.payload[1]<<8|l.payload[2])||
"GA94"!==String.fromCharCode(l.payload[3],l.payload[4],l.payload[5],l.payload[6])||3!==l.payload[7]?null:l.payload.subarray(8,l.payload.length-1)},parseCaptionPackets:function(l,e){var d=[],b;if(!(e[0]&64))return d;var a=e[0]&31;for(b=0;b<a;b++){var c=3*b;var k={type:e[c+2]&3,pts:l};e[c+2]&4&&(k.ccData=e[c+3]<<8|e[c+4],d.push(k))}return d},discardEmulationPreventionBytes:function(l){for(var e=l.byteLength,d=[],b=1,a;b<e-2;)0===l[b]&&0===l[b+1]&&3===l[b+2]?(d.push(b+2),b+=2):b++;if(0===d.length)return l;
e-=d.length;a=new Uint8Array(e);var c=0;for(b=0;b<e;c++,b++)c===d[0]&&(c++,d.shift()),a[b]=l[c];return a},USER_DATA_REGISTERED_ITU_T_T35:4}},{}],24:[function(p,y,D){y.exports=function(l){return{isLeading:(l[0]&12)>>>2,dependsOn:l[0]&3,isDependedOn:(l[1]&192)>>>6,hasRedundancy:(l[1]&48)>>>4,paddingValue:(l[1]&14)>>>1,isNonSyncSample:l[1]&1,degradationPriority:l[2]<<8|l[3]}}},{}],25:[function(p,y,D){var l=p(28).toUnsigned;y.exports=function(e){var d={version:e[0],flags:new Uint8Array(e.subarray(1,4)),
baseMediaDecodeTime:l(e[4]<<24|e[5]<<16|e[6]<<8|e[7])};1===d.version&&(d.baseMediaDecodeTime*=Math.pow(2,32),d.baseMediaDecodeTime+=l(e[8]<<24|e[9]<<16|e[10]<<8|e[11]));return d}},{28:28}],26:[function(p,y,D){y.exports=function(l){var e=new DataView(l.buffer,l.byteOffset,l.byteLength);l={version:l[0],flags:new Uint8Array(l.subarray(1,4)),trackId:e.getUint32(4)};var d=l.flags[2]&1,b=l.flags[2]&2,a=l.flags[2]&8,c=l.flags[2]&16,k=l.flags[2]&32,g=l.flags[0]&65536,m=l.flags[0]&131072;var n=8;d&&(n+=4,
l.baseDataOffset=e.getUint32(12),n+=4);b&&(l.sampleDescriptionIndex=e.getUint32(n),n+=4);a&&(l.defaultSampleDuration=e.getUint32(n),n+=4);c&&(l.defaultSampleSize=e.getUint32(n),n+=4);k&&(l.defaultSampleFlags=e.getUint32(n));g&&(l.durationIsEmpty=!0);!d&&m&&(l.baseDataOffsetIsMoof=!0);return l}},{}],27:[function(p,y,D){var l=p(24);y.exports=function(e){var d={version:e[0],flags:new Uint8Array(e.subarray(1,4)),samples:[]},b=new DataView(e.buffer,e.byteOffset,e.byteLength),a=d.flags[2]&1,c=d.flags[2]&
4,k=d.flags[1]&1,g=d.flags[1]&2,m=d.flags[1]&4,n=d.flags[1]&8,t=b.getUint32(4),h=8;a&&(d.dataOffset=b.getInt32(h),h+=4);c&&t&&(a={flags:l(e.subarray(h,h+4))},h+=4,k&&(a.duration=b.getUint32(h),h+=4),g&&(a.size=b.getUint32(h),h+=4),n&&(a.compositionTimeOffset=1===d.version?b.getInt32(h):b.getUint32(h),h+=4),d.samples.push(a),t--);for(;t--;)a={},k&&(a.duration=b.getUint32(h),h+=4),g&&(a.size=b.getUint32(h),h+=4),m&&(a.flags=l(e.subarray(h,h+4)),h+=4),n&&(a.compositionTimeOffset=1===d.version?b.getInt32(h):
b.getUint32(h),h+=4),d.samples.push(a);return d}},{24:24}],28:[function(p,y,D){y.exports={toUnsigned:function(l){return l>>>0},toHexString:function(l){return("00"+l.toString(16)).slice(-2)}}},{}],29:[function(p,y,D){var l=function(a){return 9E4*a};var e=function(a,c){return a*c};var d=function(a){return a/9E4};var b=function(a,c){return a/c};y.exports={ONE_SECOND_IN_TS:9E4,secondsToVideoTs:l,secondsToAudioTs:e,videoTsToSeconds:d,audioTsToSeconds:b,audioTsToVideoTs:function(a,c){return l(b(a,c))},
videoTsToAudioTs:function(a,c){return e(d(a),c)},metadataTsToSeconds:function(a,c,k){return d(k?a:a-c)}}},{}],30:[function(p,y,D){y.exports=function(l){var e=l.byteLength,d=0,b=0;this.length=function(){return 8*e};this.bitsAvailable=function(){return 8*e+b};this.loadWord=function(){var a=l.byteLength-e,c=new Uint8Array(4),k=Math.min(4,e);if(0===k)throw Error("no bytes available");c.set(l.subarray(a,a+k));d=(new DataView(c.buffer)).getUint32(0);b=8*k;e-=k};this.skipBits=function(a){if(!(b>a)){a-=b;
var c=Math.floor(a/8);a-=8*c;e-=c;this.loadWord()}d<<=a;b-=a};this.readBits=function(a){var c=Math.min(b,a),k=d>>>32-c;b-=c;0<b?d<<=c:0<e&&this.loadWord();c=a-c;return 0<c?k<<c|this.readBits(c):k};this.skipLeadingZeros=function(){var a;for(a=0;a<b;++a)if(0!==(d&2147483648>>>a))return d<<=a,b-=a,a;this.loadWord();return a+this.skipLeadingZeros()};this.skipUnsignedExpGolomb=function(){this.skipBits(1+this.skipLeadingZeros())};this.skipExpGolomb=function(){this.skipBits(1+this.skipLeadingZeros())};this.readUnsignedExpGolomb=
function(){var a=this.skipLeadingZeros();return this.readBits(a+1)-1};this.readExpGolomb=function(){var a=this.readUnsignedExpGolomb();return 1&a?1+a>>>1:-1*(a>>>1)};this.readBoolean=function(){return 1===this.readBits(1)};this.readUnsignedByte=function(){return this.readBits(8)};this.loadWord()}},{}],31:[function(p,y,D){p=function(){this.init=function(){var l={};this.on=function(e,d){l[e]||(l[e]=[]);l[e]=l[e].concat(d)};this.off=function(e,d){if(!l[e])return!1;var b=l[e].indexOf(d);l[e]=l[e].slice();
l[e].splice(b,1);return-1<b};this.trigger=function(e){var d,b;if(d=l[e])if(2===arguments.length){var a=d.length;for(b=0;b<a;++b)d[b].call(this,arguments[1])}else{var c=[];for(b=1;b<arguments.length;++b)c.push(arguments[b]);a=d.length;for(b=0;b<a;++b)d[b].apply(this,c)}};this.dispose=function(){l={}}}};p.prototype.pipe=function(l){this.on("data",function(e){l.push(e)});this.on("done",function(e){l.flush(e)});this.on("partialdone",function(e){l.partialFlush(e)});this.on("endedtimeline",function(e){l.endTimeline(e)});
this.on("reset",function(e){l.reset(e)});return l};p.prototype.push=function(l){this.trigger("data",l)};p.prototype.flush=function(l){this.trigger("done",l)};p.prototype.partialFlush=function(l){this.trigger("partialdone",l)};p.prototype.endTimeline=function(l){this.trigger("endedtimeline",l)};p.prototype.reset=function(l){this.trigger("reset",l)};y.exports=p},{}]},{},[17])(17)});var islocked=!1,percent,intevalde;
function lfjdownback(p,y,D){percent=100*p/y;!1===islocked&&(islocked=!0,intevalde=setInterval(function(){percent+=.01;100<=percent?(clearInterval(intevalde),islocked=!1,document.querySelector(D).innerText="joining parts"):document.querySelector(D).innerText=parseFloat(percent).toFixed(2)+"%"},170));100<=percent?(clearInterval(intevalde),document.querySelector(D).innerText="joining parts"):document.querySelector(D).innerText=parseFloat(percent).toFixed(2)+"%"}
function lfjdownload(p,y,D){function l(w){w=w||{};var q=new XMLHttpRequest;"file"===w.type&&(q.responseType="arraybuffer");q.onreadystatechange=function(){if(4===q.readyState){var z=q.status;200<=z&&300>z?w.success&&w.success(q.response):w.fail&&w.fail(z)}};q.open("GET",w.url,!0);q.send(null)}function e(w,q){q=q||location.href;if(0===w.indexOf("http"))return w;if("/"===w[0]){var z=q.split("/");return z[0]+"//"+z[2]+w}z=q.split("/");z.pop();return z.join("/")+"/"+w}function d(){alert("");l({url:E.uri,
success:function(w){E.key=E.stringToBuffer(w);E.decryptor=new AESDecryptor;E.decryptor.constructor();E.decryptor.expandKey(E.key);a()},fail:function(){alert("");n=!1}})}function b(w,q){var z=E.iv||new Uint8Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,q]);return E.decryptor.decrypt(w,0,z.buffer,!0)}function a(){for(var w=function(){var z=r;r++;lfjdownback(r,u.length,D);C[z]&&""===C[z].status?l({url:u[z],type:"file",success:function(B){c(B,z,function(){return r<u.length&&w()})},fail:function(){h++;C[z].status=
"error";r<u.length&&w()}}):r<u.length&&w()},q=0;10>q;q++)w(q)}function c(w,q,z){w=E.uri?b(w,q):w;k(w,q,function(B){A[q]=B;C[q].status="finish";f++;if(f===u.length){var J=A;B=g(t,"YYYY_MM_DD hh_mm_ss");var G=document.createElement("a");y?(J=new Blob(J,{type:"video/mp4"}),G.download=B+".mp4"):(J=new Blob(J,{type:"video/MP2T"}),G.download=B+".ts");G.href=URL.createObjectURL(J);G.style.display="none";document.body.appendChild(G);G.click();G.remove();document.querySelector(D).innerText="Done!";islocked=
!1}z&&z()})}function k(w,q,z){if(y){var B=new muxjs.Transmuxer({keepOriginalTimestamps:!0,duration:parseInt(m)});B.on("data",function(J){if(0===q){var G=new Uint8Array(J.initSegment.byteLength+J.data.byteLength);G.set(J.initSegment,0);G.set(J.data,J.initSegment.byteLength);z(G.buffer)}else z(J.data)});B.push(new Uint8Array(w));B.flush()}else z(w,q)}function g(w,q){var z={Y:w.getFullYear(),M:w.getMonth()+1,D:w.getDate(),h:w.getHours(),m:w.getMinutes(),s:w.getSeconds()};return q.replace(/Y+|M+|D+|h+|m+|s+/g,
function(B){return(Array(B.length).join("0")+z[B[0]]).substr(-B.length)})}var m=0,n=!1,t="",h=0,f=0,r=0,C=[],u=[],A=[],E={method:"",uri:"",iv:"",key:"",decryptor:null,stringToBuffer:function(w){for(var q="",z=0;z<w.length;z++)q=""===q?w.charCodeAt(z).toString(16):q+(","+w.charCodeAt(z).toString(16));return(new Uint8Array(q.match(/[\da-f]{2}/gi).map(function(B){return parseInt(B,16)}))).buffer}};!0===y&&(y=!0);(function(){p?-1===p.toLowerCase().indexOf("m3u8")?alert(""):n?alert(""):(n=!0,t=new Date,
l({url:p,success:function(w){u=[];v3u8Str=w.replace(/(#(.+)\n)/ig,"");w.split("\n").forEach(function(q){y&&-1<q.toUpperCase().indexOf("#EXTINF:")&&(m+=parseFloat(q.split("#EXTINF:")[1]));-1<q.toLowerCase().indexOf(".ts")&&(u.push(e(q,p)),C.push({title:q,status:""}),C=C.filter(Boolean))});-1<w.indexOf("#EXT-X-KEY")?(E.method=(w.match(/(.*METHOD=([^,]+))/)||["","",""])[2],E.uri=(w.match(/(.*URI="([^"]+))"/)||["","",""])[2],E.iv=(w.match(/(.*IV=([^,]+))/)||["","",""])[2],E.iv=E.iv?
E.stringToBuffer(E.iv):"",E.uri=e(E.uri,p),d()):0<u.length?a():(alert(""),n=!1)},fail:function(){alert("");n=!1}})):alert("")})()};
